# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      -  job: Building_Job
         steps:
           - task: NodeTool@0
             inputs:
               versionSource: 'spec'
               versionSpec: '20.x'
           - script: npm install
           - script: npm run build
  - stage: Test
    jobs:
      - job: Testing
        steps:
          - script: npm run test
  - stage: Deploy
    jobs:
      - job: Deploying
        steps:
          - script: npm run deploy
        